# Generated by Django 4.1.2 on 2022-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDisco', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('imDisco', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGenero', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('imagenArtista', models.ImageField(upload_to='')),
                ('discos', models.ManyToManyField(to='myapp.disco')),
                ('genero', models.ManyToManyField(to='myapp.genero')),
            ],
        ),
    ]
