# Generated by Django 4.1.2 on 2022-11-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_disco_imdisco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='fecha',
            new_name='lanzamiento',
        ),
        migrations.RemoveField(
            model_name='artistas',
            name='discos',
        ),
        migrations.AddField(
            model_name='artistas',
            name='disco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.disco'),
        ),
        migrations.RemoveField(
            model_name='artistas',
            name='genero',
        ),
        migrations.AddField(
            model_name='artistas',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.genero'),
        ),
    ]
