# Generated by Django 4.1.2 on 2022-11-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_artistas_imagenartista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='imagenArtista',
            field=models.ImageField(upload_to=''),
        ),
    ]
