<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-30 16:13
=======
# Generated by Django 4.1.2 on 2022-12-03 10:50
>>>>>>> dc72058 (act lunes 5)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_artistas_imagenartista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='imagenArtista',
<<<<<<< HEAD
            field=models.ImageField(upload_to=''),
=======
            field=models.ImageField(upload_to=None),
>>>>>>> dc72058 (act lunes 5)
        ),
    ]
