# Generated by Django 4.1.2 on 2022-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_artistas_imagenartista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='imagenArtista',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
